# ZMK Corne Configuration
# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Display Configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=n

# OLED Configuration
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_SSD1306_REVERSE_MODE=y

# Widget Configuration
CONFIG_ZMK_WIDGET_LAYER_STATUS=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# RGB Configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_STRIP_MAX_PIXELS=27

# Bluetooth Configuration
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Power Management
CONFIG_ZMK_SLEEP=y