# ZMK Corne Configuration
# Based on proven Sofle configuration
# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# OLED Display Configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Widget Configuration
CONFIG_ZMK_WIDGET_LAYER_STATUS=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# RGB Configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Especificamos el número total de LEDs (27 por lado)
CONFIG_WS2812_STRIP_MAX_PIXELS=27

# Bluetooth Configuration
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Power Management
CONFIG_ZMK_SLEEP=y

# Display Processing Configuration
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=n